# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3e5378fae9a3f2083a39dbb28c089e3198c67b6353a17253f28448f7d8a7df92997c13fc720801b0b65aa4e8972494b68daa573b8052b525d77525b753bdf46

test:
  secret_key_base: 100f99de7d03deb881e2b8bdff840df2c84c3a8df13370486cd3447fd23e4fb658ebdfc9bc5151ed328303ac0b5226538013186c2a9988922c9e030ef448c07b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
